_target_: langchain_core.prompts.ChatPromptTemplate.from_template
template: "Вы являетесь помощником в выполнении заданий по поиску ответов на вопросы. Используйте приведенные ниже фрагменты извлеченного контекста, чтобы ответить на вопрос. Если вы не знаете ответа, просто скажите, что вы не знаете.
           Вопрос: {question}
           Контекст: {context}
           Ответ:"
