_target_: langchain_community.llms.GigaChat
model: "GigaChat-Plus"
verify_ssl_certs: False
scope: "GIGACHAT_API_PERS"
credentials: "Y2Y0Yjg5OGQtMTBhMi00ZjYwLWIyYTUtY2U5YTY0ODhhYWM5OjUwMTA5YjYzLTMxYjgtNDhiZS1hNTE2LTBkMzkwN2FjNTNjZA=="
