defaults:
  - _self_
  - db: faiss
  - embedding2rag: ada_v2
  - llm2rag: gpt35_turbo
  - prompt: base
  - splitter: RecursiveCharacterTextSplitter

name: "base_rag"

test_set_path: "assets/test_set_40.csv"

file_names_for_rag_eval:
  - "assets/скан-архив/install_and_settings.docx"
  - "assets/скан-архив/usage_big.docx"
  - "assets/dozor/dozor.docx"
  - "assets/dozor/install.docx"
  - "assets/dozor/usage_big.docx"
  - "assets/dozor/usage.docx"
  - "assets/other/гендальф.docx"
