defaults:
  - neo4j: base

file_names_for_rag_eval:
  - "assets/dozor/dozor.docx"
  - "assets/скан-архив/install_and_settings.docx"
  - "assets/скан-архив/usage_big.docx"
  - "assets/dozor/install.docx"
  - "assets/dozor/usage_big.docx"
  - "assets/dozor/usage.docx"
  - "assets/other/гендальф.docx"
